ui:
  title: "Hybrid CKO Health Dashboard"
  header: "Hybrid CKO Health Dashboard"

alerting:
  slack:
    webhook-url: "https://hooks.slack.com/services/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"
    description: https://lodging-health-dashboard.rcp.us-west-2.buildtime.test.exp-aws.net/ 
    method: "POST"
    body: |
      {
        "text": "[ALERT_TRIGGERED_OR_RESOLVED]: [ENDPOINT_GROUP] - [ENDPOINT_NAME] - [ALERT_DESCRIPTION]"
      }

endpoints:
  - group: "Pricing Module12"
    name: experience-api-pricing GraphQL /isActive
    url: "https://experience-api-pricing.rcp.us-west-2.partnerexperiences.test.exp-aws.net/isActive"
    interval: 1m
    client:
      # false (default) means the server's certificate chain and host name will be verified
      insecure: true
    conditions:
      - "[STATUS] == 200"
      - "[CONNECTED] == false"
      - "[RESPONSE_TIME] < 3000"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: slack
        description: https://lodging-health-dashboard.rcp.us-west-2.buildtime.test.exp-aws.net/ 
        failure-threshold: 2
      # - test-threshold: 2
      # - enabled: true
      # - send-on-resolved: true
      # - description: "healthcheck failed"


    